[versions]
android-compile-sdk = "33"
android-min-sdk = "24"
android-target-sdk = "33"
android-gradle-plugin = "7.3.1"
activity-compose = "1.6.1"
androidx-test = "1.5.0"
androidx-test-ext = "1.1.4"
androidx-test-runner = "1.5.1"
androidx-work-manager = "2.8.0"
com-google-accompanist = "0.28.0"
compose = "1.3.1"
compose-compiler = "1.4.1"
coroutines = "1.6.4"
detekt = "1.21.0"
io-coil = "2.2.2"
java = "11"
junit = "4.13.2"
kermit = "1.2.2"
koin = "3.2.2"
koin-android = "3.3.0"
kotlin = "1.8.0"
ktor = "2.1.2"
nav-compose = "2.5.3"
turbine = "0.12.1"
versions-ben-manes = "0.44.0"
viewModel-ktx = "2.5.1"
viewModel-compose = "2.5.1"
lifecycle-runtime-compose = "2.6.0-rc01"
kotlinx-serialization = "1.4.0"
native-coroutines = "0.13.1"
androidx-compose-material3 = "1.1.0-alpha07"
androidx-compose-bom = "2023.01.00"
org-robolectric = "4.9"
sqlDelight = "1.5.5"
rss-parser = "5.0.2"
kotlinx-date-time = "0.4.0"
accompanist = "0.28.0"
jsoup = "1.15.3"
triplet-play = "3.8.1"
compose-multiplatform = "1.3.0"
decompose = "1.0.0"
jsystem-theme-detector = "3.6"

[libraries]
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidx-compose-bom" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material-icons-core = { module = "androidx.compose.material:material-icons-core" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-lifecycle-viewModel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "viewModel-ktx" }
androidx-lifecycle-viewModel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewModel-compose" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-compose" }
androidx-navigation-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "nav-compose" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-ext" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-work-manager = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work-manager" }
cashapp-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
com-google-accompanist-system-ui = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "com-google-accompanist" }
io-coil = { module = "io.coil-kt:coil", version.ref = "io-coil" }
io-coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "io-coil" }
io-gitlab-arturbosch-detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin-android" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin-android" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-kotlinx-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
touchlab-kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
org-robolectric = { module = "org.robolectric:robolectric", version.ref = "org-robolectric" }
squareup-sqldelight-android-driver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
squareup-sqldelight-coroutine-extensions = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
squareup-sqldelight-native-driver = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }
squareup-sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }
squareup-sqldelight-sqlite-driver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
com-prof18-rss-parser = { module = "com.prof18.rssparser:rssparser", version.ref = "rss-parser" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-date-time" }
accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanist" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup"  }
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-compose-jetbrains = { module = "com.arkivanov.decompose:extensions-compose-jetbrains", version.ref = "decompose" }
jsystem-theme-detector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "jsystem-theme-detector" }

[bundles]
androidx-test = ["androidx-test-core", "androidx-test-ext-junit", "androidx-test-rules", "androidx-test-runner"]
compose = [
    "androidx-activity-activity-compose", "androidx-compose-foundation", "androidx-compose-material-icons-core",
    "androidx-compose-material-icons-extended", "androidx-compose-runtime", "androidx-compose-ui",
     "androidx-compose-ui-tooling-preview", "androidx-navigation-navigation-compose",
    "androidx-compose-material3", "io-coil-compose", "accompanist-systemuicontroller",
    "androidx-lifecycle-runtime-compose", "androidx-lifecycle-viewModel-compose",
    "androidx-compose-material", "androidx-compose-ui-graphics"
]
koin = ["koin-android", "koin-compose", "koin-core"]

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
touchlab-kermit = { id = "co.touchlab.kermit", version.ref = "kermit" }
versionsBenManes = { id = "com.github.ben-manes.versions", version.ref = "versions-ben-manes" }
native-coroutines = { id = "com.rickclephas.kmp.nativecoroutines", version.ref = "native-coroutines" }
sqldelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
triplet-play = { id = "com.github.triplet.play", version.ref = "triplet-play" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }